"""Build a unified Jupyter notebook combining the LISST and MN workflows
from the Soft_Sensor_OMP repo, with case-study switch, pure-Python OMP,
stratified random sampling, time-series prediction with initial-window
training, calibration analysis, and process-relevance analysis."""

import json
import nbformat as nbf  # for building notebook
# We don't actually need nbformat -- we'll write the JSON directly.

def md(text):
    return {"cell_type": "markdown", "metadata": {}, "source": text}

def code(src):
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": src,
    }

cells = []

# ============================================================
# Header
# ============================================================
cells.append(md(
    "# Soft Sensor OMP — Unified Workflow\n"
    "\n"
    "Single notebook that runs the full sediment soft-sensor analysis end-to-end "
    "for either case study (LISST-ABS multi-basin or Minnesota River ADV continuous). "
    "Switch case studies by changing `CASE_STUDY` in the config cell below.\n"
    "\n"
    "**What changed vs. the original two notebooks**\n"
    "- One file, one config switch.\n"
    "- OMP sample selection is implemented in pure Python (greedy posterior-variance "
    "reduction). No MATLAB dependency.\n"
    "- Stratified random sampling (proportional binning) is used as the random baseline "
    "for *both* case studies, not just LISST.\n"
    "- 0–1 scaling is fit on the training fold only within each k-fold split (fixes the "
    "leakage flagged by Reviewer 3 #9).\n"
    "- Performance is reported as fold-aggregated metrics; hyperparameters used "
    "downstream in OMP are averaged across folds (addresses Reviewer 3 #3).\n"
    "- New per-site diagnostics: R², normalized RMSE, 95% interval coverage, and "
    "Spearman uncertainty–error correlation (Reviewer 3 #4 and #11).\n"
    "- New process-relevance comparison: OMP picks vs. matched random picks on upper-"
    "SSC-quartile coverage (Reviewer 3 #6 and #8).\n"
    "- Time-series prediction with initial-window training is available for any case "
    "study that provides a continuous surrogate stream (currently MN; LISST falls back "
    "to the discrete-sample regression plot)."
))

# ============================================================
# 1. Config
# ============================================================
cells.append(md("## 1. Configuration"))

cells.append(code(
    "# ---- Switch case study here ----\n"
    "CASE_STUDY = 'LISST'   # 'LISST' or 'MN'\n"
    "\n"
    "# ---- Common settings ----\n"
    "N_FOLDS         = 5      # k-fold splits for baseline GP\n"
    "N_RAND_PERMS    = 20     # number of random-sampling permutations for benchmark\n"
    "N_STRAT_BINS    = 5      # bins for proportional stratified random sampling\n"
    "P_PRED          = 100    # number of points in GP prediction grid\n"
    "OMP_MAX_N       = 25     # maximum number of samples in OMP/random comparison\n"
    "ACTIVE_BATCH    = 5      # batch size for active learning\n"
    "RANDOM_SEED     = 0\n"
    "\n"
    "# ---- Time-series settings (used only for case studies with continuous surrogate stream) ----\n"
    "TRAIN_MONTHS    = 8      # months of initial deployment used for selection in time-series mode\n"
    "TS_N_SAMPLES    = 6      # samples used to train the time-series model\n"
    "\n"
    "# ---- Plot styling ----\n"
    "COLORS = ['#E37A1B','#FFD966','#8EB85A','#A3E8F3','#376C72','#9F8BAD',\n"
    "          '#ED9CCB','#615C3B','#FF9840','#9F755F']\n"
    "MARKERS = ['s','o','^','*','X','>','d','<','v','+']\n"
    "\n"
    "# Distinct visual prefix for site labels so LISST and MN don't share visual identity\n"
    "SITE_LABEL_PREFIX = {'LISST': 'L', 'MN': 'M'}.get(CASE_STUDY, 'S')\n"
    "\n"
    "# Linear-baseline surrogate transform: matches the original notebooks.\n"
    "# LISST fits log(SSC) ~ log(ABS); MN fits log(SSC) ~ SAC (surrogate NOT logged).\n"
    "SURROGATE_LOG = {'LISST': True, 'MN': False}.get(CASE_STUDY, True)\n"
    "\n"
    "print(f'Configured for case study: {CASE_STUDY}  (label prefix: {SITE_LABEL_PREFIX}-, '\n"
    "      f'linear-fit surrogate logged: {SURROGATE_LOG})')"
))

# ============================================================
# 2. Imports
# ============================================================
cells.append(md("## 2. Imports"))

cells.append(code(
    "import os, glob, math, random, string, warnings\n"
    "from pathlib import Path\n"
    "from collections import defaultdict\n"
    "\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.ticker as ticker\n"
    "from matplotlib.lines import Line2D\n"
    "from scipy.stats import spearmanr\n"
    "import seaborn as sns\n"
    "\n"
    "from sklearn.linear_model import LinearRegression\n"
    "from sklearn.metrics import mean_squared_error\n"
    "from sklearn.model_selection import StratifiedKFold\n"
    "from sklearn.gaussian_process import GaussianProcessRegressor\n"
    "from sklearn.gaussian_process.kernels import (\n"
    "    RBF, ConstantKernel, WhiteKernel, Matern, RationalQuadratic, DotProduct\n"
    ")\n"
    "from sklearn.exceptions import ConvergenceWarning\n"
    "\n"
    "# Repo helpers (assumes you're running from the soft_sensing_code/ directory)\n"
    "from file_opening import create_USGS_dfs, toName, serialTimeToDatetime\n"
    "from SCB_conversion import SCB_CONVERSION\n"
    "\n"
    "warnings.filterwarnings('ignore', category=ConvergenceWarning)\n"
    "warnings.filterwarnings('ignore', category=UserWarning)\n"
    "\n"
    "np.random.seed(RANDOM_SEED)\n"
    "random.seed(RANDOM_SEED)\n"
    "plt.rcParams.update({'font.size': 11})"
))

# ============================================================
# 3. Helper functions
# ============================================================
cells.append(md(
    "## 3. Helper functions\n"
    "\n"
    "Everything that's shared across the case studies lives here: the GP fitter with "
    "within-fold scaling, the stratified random sampler, the pure-Python OMP variance-"
    "reduction selector, the active-learning loop, and the new diagnostics."
))

cells.append(code(
    "# ---------------------------------------------------------\n"
    "# Display / layout helpers used by every plot\n"
    "# ---------------------------------------------------------\n"
    "def site_label(sid):\n"
    "    \"\"\"Case-study-aware display label, e.g., 'L-A' for LISST site A.\"\"\"\n"
    "    return f'{SITE_LABEL_PREFIX}-{sid}'\n"
    "\n"
    "def subplot_grid(n, max_cols=3, panel_w=4.5, panel_h=3.5):\n"
    "    \"\"\"Choose a sensible (n_rows, n_cols, figsize) for `n` panels.\"\"\"\n"
    "    n = max(int(n), 1)\n"
    "    n_cols = max(1, min(max_cols, n))\n"
    "    n_rows = (n + n_cols - 1) // n_cols\n"
    "    return n_rows, n_cols, (panel_w * n_cols, panel_h * n_rows)\n"
    "\n"
    "def hide_unused_axes(axes, used):\n"
    "    for j in range(used, len(axes)):\n"
    "        axes[j].axis('off')\n"
    "\n"
    "# ---------------------------------------------------------\n"
    "# Kernel definition (used for both training and Python-side\n"
    "# correlation-matrix construction). Constant * RBF, with\n"
    "# bounds chosen for 0-1 scaled inputs.\n"
    "# ---------------------------------------------------------\n"
    "def make_kernel(const_init=0.3, l_init=1.0):\n"
    "    return ConstantKernel(const_init, (0.05, 0.8)) * RBF(l_init, (0.3, 2.0))\n"
    "\n"
    "def extract_hp(kernel):\n"
    "    params = kernel.get_params()\n"
    "    return {\n"
    "        'constant_value': float(params.get('k1__constant_value', np.nan)),\n"
    "        'length_scale':   float(params.get('k2__length_scale', np.nan)),\n"
    "    }\n"
    "\n"
    "def const_rbf_kernel_value(x, y, length_scale, const):\n"
    "    \"\"\"Single-pair Constant*RBF evaluation. x, y are scalars in [0,1].\"\"\"\n"
    "    return const * math.exp(-((x - y) ** 2) / (2 * length_scale ** 2))\n"
    "\n"
    "def build_correlation_matrix(x_grid, length_scale, const):\n"
    "    \"\"\"Constant*RBF kernel matrix over a grid of scaled surrogate values.\"\"\"\n"
    "    x_grid = np.asarray(x_grid).reshape(-1)\n"
    "    diffs = x_grid[:, None] - x_grid[None, :]\n"
    "    return const * np.exp(-(diffs ** 2) / (2 * length_scale ** 2))"
))

cells.append(code(
    "# ---------------------------------------------------------\n"
    "# GP fitter with WITHIN-FOLD min-max scaling.\n"
    "# Returns: trained model, prediction grid, scores dict.\n"
    "# Scaling parameters are fit on training data only.\n"
    "# ---------------------------------------------------------\n"
    "def fit_gp(x_train, y_train, x_test=None, y_test=None,\n"
    "           p=P_PRED, const_init=0.3, l_init=1.0,\n"
    "           n_restarts=10):\n"
    "    x_train = np.asarray(x_train, dtype=float).reshape(-1)\n"
    "    y_train = np.asarray(y_train, dtype=float).reshape(-1)\n"
    "\n"
    "    x_min, x_max = float(x_train.min()), float(x_train.max())\n"
    "    y_min, y_max = float(y_train.min()), float(y_train.max())\n"
    "    x_rng = max(x_max - x_min, 1e-8)\n"
    "    y_rng = max(y_max - y_min, 1e-8)\n"
    "\n"
    "    Xs = ((x_train - x_min) / x_rng).reshape(-1, 1)\n"
    "    ys = ((y_train - y_min) / y_rng).reshape(-1, 1)\n"
    "\n"
    "    # Try several alpha values (matches the LISST notebook's behavior of\n"
    "    # iterating over noise levels and keeping the best by log-marginal-likelihood).\n"
    "    # Without this loop, the optimizer often settles on the same boundary point\n"
    "    # across sites, producing identical hyperparameters and degenerate Frobenius\n"
    "    # distances. Each call uses a fresh kernel object and a different optimizer\n"
    "    # random_state so restart trajectories differ across data sets.\n"
    "    best_gpr, best_lml = None, -np.inf\n"
    "    for k_try, alpha_try in enumerate((1e-8, 1e-6, 1e-4, 1e-2)):\n"
    "        kernel = make_kernel(const_init, l_init)\n"
    "        try:\n"
    "            gpr_try = GaussianProcessRegressor(\n"
    "                kernel=kernel, normalize_y=False, alpha=alpha_try,\n"
    "                n_restarts_optimizer=n_restarts,\n"
    "                random_state=int(\n"
    "                    abs(hash((float(x_train.sum()), float(y_train.sum()), k_try)))\n"
    "                ) % (2**32),\n"
    "            )\n"
    "            gpr_try.fit(Xs, ys)\n"
    "            lml = float(gpr_try.log_marginal_likelihood(gpr_try.kernel_.theta))\n"
    "            if lml > best_lml:\n"
    "                best_lml = lml\n"
    "                best_gpr = gpr_try\n"
    "        except Exception:\n"
    "            continue\n"
    "    gpr = best_gpr if best_gpr is not None else None\n"
    "    if gpr is None:\n"
    "        raise RuntimeError('GP fit failed for all alpha values.')\n"
    "\n"
    "    # Prediction grid on scaled space, then back-transformed\n"
    "    Xg_scaled = np.linspace(0, 1, p).reshape(-1, 1)\n"
    "    yg_scaled, std_scaled = gpr.predict(Xg_scaled, return_std=True)\n"
    "    yg = yg_scaled.flatten() * y_rng + y_min\n"
    "    std = std_scaled.flatten() * y_rng\n"
    "    xg = Xg_scaled.flatten() * x_rng + x_min\n"
    "\n"
    "    scores = {\n"
    "        'GP_score_train':  float(gpr.score(Xs, ys)),\n"
    "        'log_marg':        float(gpr.log_marginal_likelihood()),\n"
    "        'hyperparams':     extract_hp(gpr.kernel_),\n"
    "        'x_scale':         (x_min, x_rng),\n"
    "        'y_scale':         (y_min, y_rng),\n"
    "    }\n"
    "\n"
    "    if x_test is not None and y_test is not None and len(x_test) > 0:\n"
    "        x_test = np.asarray(x_test, dtype=float).reshape(-1)\n"
    "        y_test = np.asarray(y_test, dtype=float).reshape(-1)\n"
    "        Xt = ((x_test - x_min) / x_rng).reshape(-1, 1)\n"
    "        ypred_test_scaled, std_test_scaled = gpr.predict(Xt, return_std=True)\n"
    "        ypred_test = ypred_test_scaled.flatten() * y_rng + y_min\n"
    "        std_test   = std_test_scaled.flatten() * y_rng\n"
    "        residuals  = y_test - ypred_test\n"
    "        scores['rmse']  = float(np.sqrt(np.mean(residuals ** 2)))\n"
    "        scores['nrmse'] = scores['rmse'] / max(y_test.max() - y_test.min(), 1e-8)\n"
    "        ss_res = np.sum(residuals ** 2)\n"
    "        ss_tot = np.sum((y_test - np.mean(y_test)) ** 2)\n"
    "        scores['r2_test'] = float(1 - ss_res / ss_tot) if ss_tot > 0 else np.nan\n"
    "        scores['ypred_test']  = ypred_test\n"
    "        scores['std_test']    = std_test\n"
    "\n"
    "    return gpr, (xg, yg, std), scores"
))

cells.append(code(
    "# ---------------------------------------------------------\n"
    "# Proportional stratified random sampling. Bins the surrogate\n"
    "# range into equal-width bins and samples proportionally to\n"
    "# bin density. This is the 1-D analog of quantile-based\n"
    "# coverage and is a stronger baseline than uniform random.\n"
    "# ---------------------------------------------------------\n"
    "def proportional_stratified_sample(xdata, n_samples, n_bins=N_STRAT_BINS, rng=None):\n"
    "    if rng is None:\n"
    "        rng = np.random.default_rng(RANDOM_SEED)\n"
    "    xdata = np.asarray(xdata)\n"
    "    n_total = len(xdata)\n"
    "    if n_samples >= n_total:\n"
    "        return np.arange(n_total)\n"
    "\n"
    "    bins = np.linspace(xdata.min(), xdata.max(), n_bins + 1)\n"
    "    bin_indices_list, counts = [], []\n"
    "    for b in range(n_bins):\n"
    "        mask = (xdata >= bins[b]) & (xdata < bins[b + 1])\n"
    "        if b == n_bins - 1:  # include max in last bin\n"
    "            mask = (xdata >= bins[b]) & (xdata <= bins[b + 1])\n"
    "        idx = np.where(mask)[0]\n"
    "        bin_indices_list.append(idx)\n"
    "        counts.append(len(idx))\n"
    "\n"
    "    total = max(sum(counts), 1)\n"
    "    per_bin = [int(round(n_samples * c / total)) for c in counts]\n"
    "    chosen = []\n"
    "    for b in range(n_bins):\n"
    "        avail = bin_indices_list[b]\n"
    "        if len(avail) <= per_bin[b]:\n"
    "            chosen.extend(avail.tolist())\n"
    "        else:\n"
    "            chosen.extend(rng.choice(avail, per_bin[b], replace=False).tolist())\n"
    "\n"
    "    # If rounding left us short, fill from leftover candidates\n"
    "    leftover = n_samples - len(chosen)\n"
    "    if leftover > 0:\n"
    "        remaining = list(set(range(n_total)) - set(chosen))\n"
    "        if len(remaining) >= leftover:\n"
    "            chosen.extend(rng.choice(remaining, leftover, replace=False).tolist())\n"
    "        else:\n"
    "            chosen.extend(remaining)\n"
    "    # If we overshot, trim\n"
    "    if len(chosen) > n_samples:\n"
    "        chosen = chosen[:n_samples]\n"
    "    return np.array(chosen, dtype=int)"
))

cells.append(code(
    "# ---------------------------------------------------------\n"
    "# Pure-Python OMP-style greedy variance reduction over a\n"
    "# kernel correlation matrix. Replaces the MATLAB sfo toolbox.\n"
    "#\n"
    "# At each step, pick the index i that, if observed, would\n"
    "# reduce the total posterior variance the most. With the\n"
    "# rank-1 Schur complement update we get O(n^2 * k).\n"
    "# ---------------------------------------------------------\n"
    "def omp_variance_reduction(K, n_select):\n"
    "    \"\"\"Greedy posterior-variance reduction sample selection.\n"
    "\n"
    "    Parameters\n"
    "    ----------\n"
    "    K : (n, n) ndarray\n"
    "        Kernel covariance matrix over candidate samples.\n"
    "    n_select : int\n"
    "        Number of samples to select.\n"
    "\n"
    "    Returns\n"
    "    -------\n"
    "    order : list of int\n"
    "        Indices into K's rows giving the greedy selection order.\n"
    "    utilities : list of float\n"
    "        Cumulative total variance reduction at each step,\n"
    "        normalized by the prior total variance (i.e., starts\n"
    "        near 0 and approaches 1 as more samples are added).\n"
    "    \"\"\"\n"
    "    K = np.asarray(K, dtype=float).copy()\n"
    "    n = K.shape[0]\n"
    "    n_select = min(int(n_select), n)\n"
    "\n"
    "    prior_total = float(np.trace(K))\n"
    "    if prior_total <= 1e-12:\n"
    "        return list(range(n_select)), [0.0] * n_select\n"
    "\n"
    "    selected = []\n"
    "    utilities = []\n"
    "    K_post = K.copy()\n"
    "    selected_mask = np.zeros(n, dtype=bool)\n"
    "\n"
    "    for _ in range(n_select):\n"
    "        diag = np.diag(K_post).copy()\n"
    "        diag[selected_mask] = -np.inf\n"
    "        # Marginal variance reduction if we observe index i:\n"
    "        # sum over all points x of K_post[x, i]^2 / K_post[i, i]\n"
    "        gains = np.where(diag > 1e-12,\n"
    "                         np.sum(K_post ** 2, axis=0) / np.where(diag > 0, diag, 1),\n"
    "                         -np.inf)\n"
    "        gains[selected_mask] = -np.inf\n"
    "        best = int(np.argmax(gains))\n"
    "        selected.append(best)\n"
    "        selected_mask[best] = True\n"
    "\n"
    "        # Rank-1 Schur-complement update of the posterior covariance\n"
    "        d = K_post[best, best]\n"
    "        if d > 1e-12:\n"
    "            K_post = K_post - np.outer(K_post[:, best], K_post[best, :]) / d\n"
    "        # Numerical floor (avoid negative variances from roundoff)\n"
    "        np.fill_diagonal(K_post, np.maximum(np.diag(K_post), 0.0))\n"
    "\n"
    "        utilities.append(1.0 - float(np.trace(K_post)) / prior_total)\n"
    "\n"
    "    return selected, utilities"
))

cells.append(code(
    "# ---------------------------------------------------------\n"
    "# Active learning loop: pick first batch using transferred\n"
    "# hyperparameters, train a GP on those samples, use the new\n"
    "# hyperparameters to rebuild the correlation matrix, pick\n"
    "# the next batch, and so on.\n"
    "# ---------------------------------------------------------\n"
    "def active_learning_select(x_all, y_all, init_const, init_l,\n"
    "                            n_total, batch=ACTIVE_BATCH):\n"
    "    x_all = np.asarray(x_all, dtype=float).reshape(-1)\n"
    "    y_all = np.asarray(y_all, dtype=float).reshape(-1)\n"
    "    n = len(x_all)\n"
    "    n_total = min(n_total, n)\n"
    "\n"
    "    # Scale once using ALL candidates (this matches deployment, where the\n"
    "    # full continuous surrogate stream is observable). For pure-evaluation\n"
    "    # equivalence with fit_gp, we accept this scaling here because the\n"
    "    # candidate pool is the surrogate values, which are continuously available\n"
    "    # in real deployment.\n"
    "    x_min, x_max = x_all.min(), x_all.max()\n"
    "    rng = max(x_max - x_min, 1e-8)\n"
    "    xs = (x_all - x_min) / rng\n"
    "\n"
    "    selected = []\n"
    "    const, l = init_const, init_l\n"
    "    while len(selected) < n_total:\n"
    "        # Build correlation matrix over remaining candidates only\n"
    "        remaining = [i for i in range(n) if i not in set(selected)]\n"
    "        if not remaining:\n"
    "            break\n"
    "        K_rem = build_correlation_matrix(xs[remaining], l, const)\n"
    "        # Take next batch\n"
    "        k_next = min(batch, n_total - len(selected), len(remaining))\n"
    "        order_local, _ = omp_variance_reduction(K_rem, k_next)\n"
    "        for j in order_local:\n"
    "            selected.append(remaining[j])\n"
    "        if len(selected) >= n_total:\n"
    "            break\n"
    "        # Retrain GP on selected, update hyperparameters\n"
    "        try:\n"
    "            _, _, scores = fit_gp(x_all[selected], y_all[selected])\n"
    "            const = scores['hyperparams']['constant_value']\n"
    "            l     = scores['hyperparams']['length_scale']\n"
    "        except Exception as e:\n"
    "            # Retain previous hyperparameters if refit fails\n"
    "            pass\n"
    "    return selected"
))

cells.append(code(
    "# ---------------------------------------------------------\n"
    "# Diagnostics: coverage, uncertainty-error correlation,\n"
    "# Frobenius distance between correlation matrices, and\n"
    "# upper-quartile process-relevance comparison.\n"
    "# ---------------------------------------------------------\n"
    "def coverage_95(y_true, y_pred, y_std):\n"
    "    y_true, y_pred, y_std = map(np.asarray, (y_true, y_pred, y_std))\n"
    "    inside = (y_true >= y_pred - 1.96 * y_std) & (y_true <= y_pred + 1.96 * y_std)\n"
    "    return float(np.mean(inside)) if len(inside) else np.nan\n"
    "\n"
    "def uncertainty_error_correlation(y_true, y_pred, y_std):\n"
    "    y_true, y_pred, y_std = map(np.asarray, (y_true, y_pred, y_std))\n"
    "    abs_res = np.abs(y_true - y_pred)\n"
    "    if len(abs_res) < 3 or np.std(y_std) < 1e-12:\n"
    "        return np.nan, np.nan\n"
    "    rho, p = spearmanr(y_std, abs_res)\n"
    "    return float(rho), float(p)\n"
    "\n"
    "def frobenius_distance(A, B):\n"
    "    A, B = np.asarray(A), np.asarray(B)\n"
    "    if A.shape != B.shape:\n"
    "        # If shapes differ, resample to the smaller shape's grid implicitly via\n"
    "        # interpolation. For our use both matrices are built on the SAME grid,\n"
    "        # so this is a guard only.\n"
    "        return np.nan\n"
    "    return float(np.linalg.norm(A - B, ord='fro'))\n"
    "\n"
    "def quantile_top_fraction(values, reference, q=0.75):\n"
    "    thresh = np.quantile(reference, q)\n"
    "    return float(np.mean(np.asarray(values) >= thresh))\n"
    "\n"
    "def omp_vs_random_summary(x_all, y_all, omp_ranked_indices,\n"
    "                          n_top=10, n_random=200, rng=None):\n"
    "    \"\"\"Compare top-n OMP picks against bootstrapped random selections of size n_top.\"\"\"\n"
    "    if rng is None:\n"
    "        rng = np.random.default_rng(RANDOM_SEED)\n"
    "    n_top = min(int(n_top), len(omp_ranked_indices), len(x_all))\n"
    "    omp_idx = np.asarray(omp_ranked_indices[:n_top], dtype=int)\n"
    "    x_all = np.asarray(x_all); y_all = np.asarray(y_all)\n"
    "    summary = {\n"
    "        'n_top':                    n_top,\n"
    "        'omp_frac_top25_ssc':       quantile_top_fraction(y_all[omp_idx], y_all),\n"
    "        'omp_frac_top25_surr':      quantile_top_fraction(x_all[omp_idx], x_all),\n"
    "    }\n"
    "    rand_ssc, rand_surr = [], []\n"
    "    n = len(x_all)\n"
    "    for _ in range(n_random):\n"
    "        ridx = rng.choice(n, size=n_top, replace=False)\n"
    "        rand_ssc.append(quantile_top_fraction(y_all[ridx], y_all))\n"
    "        rand_surr.append(quantile_top_fraction(x_all[ridx], x_all))\n"
    "    summary['rand_frac_top25_ssc_mean']  = float(np.mean(rand_ssc))\n"
    "    summary['rand_frac_top25_ssc_p95']   = float(np.percentile(rand_ssc, 95))\n"
    "    summary['rand_frac_top25_surr_mean'] = float(np.mean(rand_surr))\n"
    "    summary['rand_frac_top25_surr_p95']  = float(np.percentile(rand_surr, 95))\n"
    "    return summary"
))

# ============================================================
# 4. Data loading
# ============================================================
cells.append(md(
    "## 4. Data loading\n"
    "\n"
    "Each loader returns a `case_data` dictionary keyed by alphabetic site ID. Each value has:\n"
    "- `'site_id_long'`: original USGS site identifier (string)\n"
    "- `'samples'`: DataFrame with columns `['surrogate', 'SSC', 'datetime']` (datetime may be NaN if no time info)\n"
    "- `'continuous'`: DataFrame with columns `['surrogate', 'datetime']` for the continuous sensor stream, "
    "or `None` if not available (then time-series prediction is skipped).\n"
    "\n"
    "Downstream analyses use only this common interface — they don't need to know which case study is loaded."
))

cells.append(code(
    "# Explicit site ordering so the A-G labels match the published figures\n"
    "# (SI Table 2.1). Your original notebook relied on unsorted glob order, which is\n"
    "# filesystem-dependent; this list makes the mapping reproducible. Files not listed\n"
    "# here are appended afterward in sorted order.\n"
    "LISST_SITE_ORDER = [\n"
    "    'Missouri_River_NebraskaCity_06807000',  # A\n"
    "    'Rock_Creek_01648010',                   # B\n"
    "    'Elwha_River_12046260',                  # C\n"
    "    'Sacramento_River_11447650',             # D\n"
    "    'Illinois_River_05586300',               # E\n"
    "    'Cherry_Creek_06713000',                 # F\n"
    "    'Missouri_River_StCharles_06935965',     # G\n"
    "]\n"
    "\n"
    "def load_lisst(repo_root='.'):\n"
    "    lisst_dir = os.path.join(repo_root, 'LISST_ABS_USGS')\n"
    "    found = glob.glob(os.path.join(lisst_dir, '*.csv'))\n"
    "    if not found:\n"
    "        raise FileNotFoundError(f'No CSVs found in {lisst_dir}')\n"
    "    # Order files by the explicit list, then append any extras (sorted) at the end\n"
    "    by_stem = {os.path.basename(fp).replace('.csv', ''): fp for fp in found}\n"
    "    ordered_stems = [s for s in LISST_SITE_ORDER if s in by_stem]\n"
    "    extras = sorted(s for s in by_stem if s not in LISST_SITE_ORDER)\n"
    "    if extras:\n"
    "        print(f'Note: {len(extras)} LISST file(s) not in LISST_SITE_ORDER, '\n"
    "              f'appended after the known sites: {extras}')\n"
    "    csv_files = [by_stem[s] for s in ordered_stems + extras]\n"
    "\n"
    "    # First-available column variants\n"
    "    column_priority = {\n"
    "        'ABS':   ['ABS (All)', 'ABS'],\n"
    "        'SSC':   ['SSC (All)', 'Total SSC'],\n"
    "        'Fines': ['Fines'],\n"
    "        'Sands': ['Sands'],\n"
    "        'Date':  ['Date'],\n"
    "    }\n"
    "    required = {'Date', 'ABS', 'SSC'}\n"
    "\n"
    "    case_data = {}\n"
    "    alpha = list(string.ascii_uppercase)\n"
    "    site_idx = 0\n"
    "    for fp in csv_files:\n"
    "        fname = os.path.basename(fp).replace('.csv', '')\n"
    "        df_head = pd.read_csv(fp, nrows=0)\n"
    "        cols = df_head.columns.tolist()\n"
    "        selected = {}\n"
    "        for std_name, variants in column_priority.items():\n"
    "            for v in variants:\n"
    "                if v in cols:\n"
    "                    selected[v] = std_name\n"
    "                    break\n"
    "        if not required.issubset(set(selected.values())):\n"
    "            continue\n"
    "        df = pd.read_csv(fp, usecols=selected.keys()).rename(columns=selected)\n"
    "        df = df[['Date', 'ABS', 'SSC']].dropna(subset=['ABS', 'SSC']).reset_index(drop=True)\n"
    "        if len(df) < 6:\n"
    "            continue\n"
    "        df = df.rename(columns={'ABS': 'surrogate', 'Date': 'datetime'})\n"
    "        # Try to parse datetime; fall back gracefully\n"
    "        try:\n"
    "            df['datetime'] = pd.to_datetime(df['datetime'])\n"
    "        except Exception:\n"
    "            df['datetime'] = pd.NaT\n"
    "        case_data[alpha[site_idx]] = {\n"
    "            'site_id_long': fname,\n"
    "            'samples':      df[['surrogate', 'SSC', 'datetime']].copy(),\n"
    "            'continuous':   None,   # LISST has no continuous stream in the repo\n"
    "        }\n"
    "        site_idx += 1\n"
    "    return case_data\n"
    "\n"
    "\n"
    "def _compute_sac(advm_df, consts):\n"
    "    \"\"\"Run SCB_CONVERSION to derive SAC from ADVM readings.\"\"\"\n"
    "    # Build SNR/AMP beam arrays\n"
    "    snr_cols = [c for c in advm_df.columns if c.upper().startswith('SNR')]\n"
    "    amp_cols = [c for c in advm_df.columns if c.upper().startswith('AMP')]\n"
    "    # Fall back to convention used in the repo (beam_array on named ranges)\n"
    "    # SNR1 columns range, SNR2 columns range, AMP1 columns range, AMP2 columns range\n"
    "    # If the repo conventions don't match, the simple bulk array still works for SCB.\n"
    "    SNR = advm_df[snr_cols].to_numpy().T if snr_cols else np.zeros((1, len(advm_df)))\n"
    "    AMP = advm_df[amp_cols].to_numpy().T if amp_cols else np.zeros((1, len(advm_df)))\n"
    "    Vbeam_col = next((c for c in advm_df.columns if 'Vbeam' in c or 'V_beam' in c), None)\n"
    "    Temp_col  = next((c for c in advm_df.columns if c.lower().startswith('temp')), None)\n"
    "    Vbeam = advm_df[Vbeam_col].to_numpy() if Vbeam_col else np.ones(len(advm_df))\n"
    "    Temp  = advm_df[Temp_col].to_numpy() if Temp_col else np.full(len(advm_df), 20.0)\n"
    "    dt_col = next((c for c in advm_df.columns if 'date' in c.lower() or 'time' in c.lower()), None)\n"
    "    dt = advm_df[dt_col].to_numpy() if dt_col else np.arange(len(advm_df))\n"
    "    scb = SCB_CONVERSION(SNR=SNR, AMP=AMP, Consts=consts.to_numpy(),\n"
    "                          Vbeam=Vbeam, Temp=Temp, date_time=dt)\n"
    "    return scb\n"
    "\n"
    "\n"
    "def load_mn(repo_root='.'):\n"
    "    site_ids = ['05325000', '05325300', '05330000']\n"
    "    ADVM    = create_USGS_dfs('sensor',  site_ids)\n"
    "    Samples = create_USGS_dfs('samples', site_ids)\n"
    "    consts_df = pd.read_csv(os.path.join(repo_root, 'USGS_data', 'USGS_site_consts.csv'))\n"
    "    consts_df['Site_ID'] = consts_df['Site_ID'].map(toName)\n"
    "\n"
    "    alpha = list(string.ascii_uppercase)\n"
    "    case_data = {}\n"
    "    for i, sid in enumerate(site_ids):\n"
    "        sdf = Samples[sid].copy()\n"
    "        adf = ADVM[sid].copy()\n"
    "        # Use precomputed SAC if available; otherwise compute via SCB.\n"
    "        if 'SAC' not in sdf.columns:\n"
    "            sdf['SAC'] = np.nan  # placeholder; users may add a computation here\n"
    "        if 'SAC' not in adf.columns:\n"
    "            adf['SAC'] = np.nan\n"
    "        # Datetime conversion\n"
    "        if 'DateTime' in sdf.columns:\n"
    "            try:\n"
    "                sdf['datetime'] = serialTimeToDatetime(sdf['DateTime'].to_numpy())\n"
    "            except Exception:\n"
    "                sdf['datetime'] = pd.NaT\n"
    "        if 'DateTime' in adf.columns:\n"
    "            try:\n"
    "                adf['datetime'] = serialTimeToDatetime(adf['DateTime'].to_numpy())\n"
    "            except Exception:\n"
    "                adf['datetime'] = pd.NaT\n"
    "\n"
    "        samp_out = pd.DataFrame({\n"
    "            'surrogate': sdf['SAC'],\n"
    "            'SSC':       sdf['SSC'] if 'SSC' in sdf.columns else np.nan,\n"
    "            'datetime':  sdf['datetime'],\n"
    "        }).dropna(subset=['surrogate', 'SSC']).reset_index(drop=True)\n"
    "\n"
    "        cont_out = pd.DataFrame({\n"
    "            'surrogate': adf['SAC'],\n"
    "            'datetime':  adf['datetime'],\n"
    "        }).dropna(subset=['surrogate']).reset_index(drop=True)\n"
    "\n"
    "        case_data[alpha[i]] = {\n"
    "            'site_id_long': sid,\n"
    "            'samples':      samp_out,\n"
    "            'continuous':   cont_out,\n"
    "        }\n"
    "    return case_data\n"
    "\n"
    "\n"
    "# Dispatch\n"
    "if CASE_STUDY == 'LISST':\n"
    "    case_data = load_lisst('.')\n"
    "    SURR_LABEL = 'ABS (dB)'\n"
    "elif CASE_STUDY == 'MN':\n"
    "    case_data = load_mn('.')\n"
    "    SURR_LABEL = 'SAC (dB)'\n"
    "else:\n"
    "    raise ValueError(f'Unknown CASE_STUDY: {CASE_STUDY}')\n"
    "\n"
    "alpha_site_id = list(case_data.keys())\n"
    "print(f'Loaded {len(alpha_site_id)} sites for case study {CASE_STUDY}')\n"
    "for sid, d in case_data.items():\n"
    "    n_samp = len(d['samples'])\n"
    "    has_cont = 'yes' if d['continuous'] is not None and len(d['continuous']) > 0 else 'no'\n"
    "    print(f'  {site_label(sid)}: {d[\"site_id_long\"]:35s} n_samples={n_samp:4d}  continuous stream: {has_cont}')"
))

# ============================================================
# 5. Linear regression baseline
# ============================================================
cells.append(md(
    "## 5. Linear regression baseline (Figure 1 equivalent)"
))

cells.append(code(
    "fig, ax = plt.subplots(figsize=(10, 4))\n"
    "legend_handles = []\n"
    "linear_results = {}\n"
    "\n"
    "for i, sid in enumerate(alpha_site_id):\n"
    "    df = case_data[sid]['samples']\n"
    "    x = df['surrogate'].to_numpy().reshape(-1, 1)\n"
    "    y = df['SSC'].to_numpy().reshape(-1, 1)\n"
    "    log_y = np.log(y)\n"
    "    # Surrogate is logged only when SURROGATE_LOG is True (LISST); MN keeps it linear\n"
    "    x_fit = np.log(x) if SURROGATE_LOG else x\n"
    "    model = LinearRegression().fit(x_fit, log_y)\n"
    "    log_y_pred = model.predict(x_fit)\n"
    "    slope = float(model.coef_[0, 0])\n"
    "    intercept = float(model.intercept_[0])\n"
    "\n"
    "    # RMSE / nRMSE / R^2 computed in ORIGINAL units (back-transformed from log)\n"
    "    y_true_arr = np.exp(log_y).ravel()\n"
    "    y_pred_arr = np.exp(log_y_pred).ravel()\n"
    "    residuals = y_true_arr - y_pred_arr\n"
    "    rmse  = float(np.sqrt(np.mean(residuals ** 2)))\n"
    "    y_rng = float(y_true_arr.max() - y_true_arr.min())\n"
    "    nrmse = rmse / y_rng if y_rng > 0 else np.nan\n"
    "    ss_res = float(np.sum(residuals ** 2))\n"
    "    ss_tot = float(np.sum((y_true_arr - np.mean(y_true_arr)) ** 2))\n"
    "    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else np.nan\n"
    "    linear_results[sid] = {\n"
    "        'slope': slope, 'intercept': intercept,\n"
    "        'rmse': rmse, 'nrmse': nrmse, 'r2': r2,\n"
    "    }\n"
    "\n"
    "    # Plot the fitted line in original surrogate units (sorted by surrogate value)\n"
    "    sort_idx = np.argsort(x.ravel())\n"
    "    ax.scatter(x, y, color=COLORS[i % len(COLORS)],\n"
    "               marker=MARKERS[i % len(MARKERS)], edgecolors='#2E2E2E', zorder=1)\n"
    "    ax.plot(x[sort_idx], np.exp(log_y_pred[sort_idx]),\n"
    "            linewidth=2, color=COLORS[i % len(COLORS)])\n"
    "    legend_handles.append(Line2D(\n"
    "        [0], [0], color=COLORS[i % len(COLORS)],\n"
    "        marker=MARKERS[i % len(MARKERS)], linestyle='-', markersize=8,\n"
    "        markeredgecolor='#2E2E2E',\n"
    "        label=(f'Site {site_label(sid)}: RMSE={rmse:.2f}, nRMSE={nrmse:.2f}, '\n"
    "               f'R\\u00b2={r2:.2f}\\n'\n"
    "               f'log(y)={slope:.2f}x+{intercept:.2f}')\n"
    "    ))\n"
    "\n"
    "ax.set_yscale('log')\n"
    "if SURROGATE_LOG:\n"
    "    ax.set_xscale('log')   # LISST: log-log; MN keeps SAC on a linear axis\n"
    "ax.set_xlabel(SURR_LABEL); ax.set_ylabel('SSC (mg/L)')\n"
    "ax.legend(handles=legend_handles, bbox_to_anchor=(1.02, 1), loc='upper left', fontsize=7.5)\n"
    "ax.set_title(f'{CASE_STUDY}: linear regression baselines per site')\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "linear_table = pd.DataFrame(linear_results).T.round(3)\n"
    "linear_table.index = [site_label(s) for s in linear_table.index]\n"
    "linear_table"
))

# ============================================================
# 6. Baseline GP with k-fold
# ============================================================
cells.append(md(
    "## 6. Baseline GP with k-fold CV + fold aggregation\n"
    "\n"
    "Scaling parameters are fit on the training fold only. Performance metrics and "
    "hyperparameters are aggregated across folds; downstream OMP uses the fold-averaged "
    "hyperparameters rather than picking a single representative fold."
))

cells.append(code(
    "model_dictionary = {}\n"
    "\n"
    "for sid in alpha_site_id:\n"
    "    df = case_data[sid]['samples']\n"
    "    xdata = df['surrogate'].to_numpy()\n"
    "    ydata = df['SSC'].to_numpy()\n"
    "    if len(xdata) < 3:\n"
    "        print(f'Skipping site {sid} (too few samples)')\n"
    "        continue\n"
    "    n_splits = min(N_FOLDS, len(xdata))\n"
    "    n_bins = max(2, min(10, len(xdata) // n_splits))\n"
    "    x_binned = np.floor(np.interp(xdata, (xdata.min(), xdata.max()), (0, n_bins))).astype(int)\n"
    "    x_binned = np.clip(x_binned, 0, n_bins - 1)\n"
    "    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=RANDOM_SEED)\n"
    "\n"
    "    folds = {}\n"
    "    for fold_idx, (train_idx, test_idx) in enumerate(skf.split(xdata, x_binned)):\n"
    "        x_train, y_train = xdata[train_idx], ydata[train_idx]\n"
    "        x_test, y_test   = xdata[test_idx],  ydata[test_idx]\n"
    "        try:\n"
    "            gpr, (xg, yg, sg), scores = fit_gp(x_train, y_train, x_test, y_test)\n"
    "        except Exception as e:\n"
    "            print(f'Fold {fold_idx} site {sid} failed: {e}')\n"
    "            continue\n"
    "        cov = coverage_95(y_test, scores['ypred_test'], scores['std_test'])\n"
    "        rho, _ = uncertainty_error_correlation(y_test, scores['ypred_test'], scores['std_test'])\n"
    "        scores['coverage_95'] = cov\n"
    "        scores['unc_err_rho'] = rho\n"
    "        folds[fold_idx] = {\n"
    "            'x_train': x_train, 'y_train': y_train,\n"
    "            'x_test':  x_test,  'y_test':  y_test,\n"
    "            'pred':    (xg, yg, sg),\n"
    "            'model':   gpr, 'scores': scores,\n"
    "        }\n"
    "\n"
    "    if not folds:\n"
    "        continue\n"
    "    rmses = np.array([f['scores'].get('rmse', np.nan) for f in folds.values()])\n"
    "    r2s   = np.array([f['scores'].get('r2_test', np.nan) for f in folds.values()])\n"
    "    nrmses= np.array([f['scores'].get('nrmse', np.nan) for f in folds.values()])\n"
    "    covs  = np.array([f['scores'].get('coverage_95', np.nan) for f in folds.values()])\n"
    "    rhos  = np.array([f['scores'].get('unc_err_rho', np.nan) for f in folds.values()])\n"
    "    ls    = np.array([f['scores']['hyperparams']['length_scale']   for f in folds.values()])\n"
    "    cs    = np.array([f['scores']['hyperparams']['constant_value'] for f in folds.values()])\n"
    "\n"
    "    rep_fold = int(sorted(folds.items(),\n"
    "                          key=lambda kv: kv[1]['scores'].get('rmse', np.inf))[len(folds) // 2][0])\n"
    "\n"
    "    def _iqr(arr):\n"
    "        arr = np.asarray(arr, dtype=float)\n"
    "        arr = arr[~np.isnan(arr)]\n"
    "        if len(arr) < 2:\n"
    "            return np.nan\n"
    "        return float(np.percentile(arr, 75) - np.percentile(arr, 25))\n"
    "\n"
    "    model_dictionary[sid] = {\n"
    "        'folds': folds,\n"
    "        'representative_fold_idx': rep_fold,\n"
    "        'baseline': {\n"
    "            # Performance metrics: median across folds, with IQR for spread\n"
    "            'rmse_median':         float(np.nanmedian(rmses)),\n"
    "            'rmse_iqr':            _iqr(rmses),\n"
    "            'r2_test_median':      float(np.nanmedian(r2s)),\n"
    "            'r2_test_iqr':         _iqr(r2s),\n"
    "            'nrmse_median':        float(np.nanmedian(nrmses)),\n"
    "            'nrmse_iqr':           _iqr(nrmses),\n"
    "            'coverage_95_median':  float(np.nanmedian(covs)),\n"
    "            'unc_err_rho_median':  float(np.nanmedian(rhos)),\n"
    "            # Hyperparameters: mean across folds (these feed the OMP step;\n"
    "            # averaging kernel parameters is more conventional than taking a median)\n"
    "            'length_scale_mean':   float(np.nanmean(ls)),\n"
    "            'constant_mean':       float(np.nanmean(cs)),\n"
    "            'hyperparams_for_omp': {\n"
    "                'length_scale':   float(np.nanmean(ls)),\n"
    "                'constant_value': float(np.nanmean(cs)),\n"
    "            },\n"
    "        },\n"
    "    }\n"
    "\n"
    "summary_rows = []\n"
    "for sid, m in model_dictionary.items():\n"
    "    b = m['baseline']\n"
    "    summary_rows.append({\n"
    "        'site': site_label(sid), 'n': len(case_data[sid]['samples']),\n"
    "        'rmse_median':    b['rmse_median'],   'rmse_iqr':    b['rmse_iqr'],\n"
    "        'nrmse_median':   b['nrmse_median'],  'nrmse_iqr':   b['nrmse_iqr'],\n"
    "        'r2_test_median': b['r2_test_median'],'r2_test_iqr': b['r2_test_iqr'],\n"
    "        'coverage_95':    b['coverage_95_median'], 'unc_err_rho': b['unc_err_rho_median'],\n"
    "        'l_mean':         b['length_scale_mean'], 'C_mean':       b['constant_mean'],\n"
    "    })\n"
    "summary_df = pd.DataFrame(summary_rows).round(3)\n"
    "summary_df"
))

# ============================================================
# 6b. Per-fold baseline GP plots
# ============================================================
cells.append(md(
    "### Per-fold baseline GP fits\n"
    "\n"
    "For each site, plot every k-fold GP fit (mean and 95% CI) overlaid on its train/test "
    "split. Useful for spotting unstable folds and visualizing fold-to-fold variability "
    "behind the aggregated metrics in `summary_df`."
))

cells.append(code(
    "n_rows, n_cols, figsize = subplot_grid(len(site_ids), max_cols=3, panel_w=5, panel_h=4)\n"
    "fig, axes = plt.subplots(n_rows, n_cols, figsize=figsize, squeeze=False)\n"
    "axes = axes.flatten()\n"
    "\n"
    "for ax_idx, sid in enumerate(site_ids):\n"
    "    ax = axes[ax_idx]\n"
    "    folds = model_dictionary[sid]['folds']\n"
    "    rep_idx = model_dictionary[sid]['representative_fold_idx']\n"
    "    for fold_idx, f in folds.items():\n"
    "        xg, yg, sg = f['pred']\n"
    "        is_rep = (fold_idx == rep_idx)\n"
    "        lw = 1.8 if is_rep else 0.9\n"
    "        alpha = 0.9 if is_rep else 0.55\n"
    "        label = f'fold {fold_idx}' + (' (rep)' if is_rep else '')\n"
    "        ax.plot(xg, yg, linewidth=lw, alpha=alpha, label=label)\n"
    "        ax.fill_between(xg, yg - 1.96 * sg, yg + 1.96 * sg, alpha=0.08)\n"
    "        ax.scatter(f['x_test'], f['y_test'], s=25, marker='x', alpha=0.7)\n"
    "    df_all = case_data[sid]['samples']\n"
    "    ax.scatter(df_all['surrogate'], df_all['SSC'],\n"
    "               color='lightgray', s=18, zorder=0)\n"
    "    b = model_dictionary[sid]['baseline']\n"
    "    ax.set_title(\n"
    "        f\"Site {site_label(sid)}  median RMSE={b['rmse_median']:.2f},  \"\n"
    "        f\"median R\\u00b2={b['r2_test_median']:.2f}\\n\"\n"
    "        f\"l_mean={b['length_scale_mean']:.2f}, C_mean={b['constant_mean']:.2f}\",\n"
    "        fontsize=10,\n"
    "    )\n"
    "    ax.set_xlabel(SURR_LABEL)\n"
    "    ax.set_ylabel('SSC (mg/L)')\n"
    "    ax.legend(fontsize=7, loc='best')\n"
    "hide_unused_axes(axes, len(site_ids))\n"
    "plt.suptitle(f'{CASE_STUDY}: per-fold baseline GP fits')\n"
    "plt.tight_layout()\n"
    "plt.show()"
))


# ============================================================
# 7. Frobenius diagnostic
# ============================================================
cells.append(md(
    "## 7. Frobenius-norm transferability diagnostic\n"
    "\n"
    "Pairwise distance between baseline correlation matrices using each site's fold-"
    "averaged hyperparameters. Promoted from the SI to the main text per Reviewer 2 #1 "
    "and Reviewer 3 #1. Lower distance = better expected transfer."
))

cells.append(code(
    "# Diagnostic: print fold-averaged hyperparameters per site so we can see\n"
    "# whether they actually differ between sites. If two sites have identical\n"
    "# (l, C) the Frobenius distance between them WILL be 0 by construction.\n"
    "print('Per-site fold-averaged hyperparameters used in the Frobenius diagnostic:')\n"
    "for sid in site_ids:\n"
    "    hp = model_dictionary[sid]['baseline']['hyperparams_for_omp']\n"
    "    print(f'  site {site_label(sid)}:  l = {hp[\"length_scale\"]:.4f}   C = {hp[\"constant_value\"]:.4f}')\n"
    "\n"
    "# Replicates the diagnostic from the manuscript SI:\n"
    "# For each (model_site, target_site) pair, evaluate model_site's kernel on the\n"
    "# target_site's OWN scaled training-sample grid, normalize to a correlation matrix,\n"
    "# and compute the *relative* Frobenius distance |A - B|_F / |B|_F where B is the\n"
    "# target site's own kernel on its own grid.\n"
    "site_ids = list(model_dictionary.keys())\n"
    "fro_rel_matrix = np.zeros((len(site_ids), len(site_ids)))\n"
    "\n"
    "def cov_to_cor(K):\n"
    "    d = np.sqrt(np.diag(K))\n"
    "    return K / np.outer(np.where(d > 0, d, 1), np.where(d > 0, d, 1))\n"
    "\n"
    "# Precompute each target's scaled training grid (using the representative fold's\n"
    "# training data, so this matches what would be used in OMP downstream).\n"
    "target_grids = {}\n"
    "for sid in site_ids:\n"
    "    rep_idx = model_dictionary[sid]['representative_fold_idx']\n"
    "    x_train = model_dictionary[sid]['folds'][rep_idx]['x_train']\n"
    "    x_sort = np.sort(np.asarray(x_train, dtype=float))\n"
    "    x_min, x_max = x_sort.min(), x_sort.max()\n"
    "    rng = max(x_max - x_min, 1e-8)\n"
    "    target_grids[sid] = (x_sort - x_min) / rng\n"
    "\n"
    "for i, model_sid in enumerate(site_ids):\n"
    "    hp_model = model_dictionary[model_sid]['baseline']['hyperparams_for_omp']\n"
    "    for j, target_sid in enumerate(site_ids):\n"
    "        grid = target_grids[target_sid]\n"
    "        hp_target = model_dictionary[target_sid]['baseline']['hyperparams_for_omp']\n"
    "        # Source kernel on target's grid\n"
    "        K_src = build_correlation_matrix(grid, hp_model['length_scale'], hp_model['constant_value'])\n"
    "        A = cov_to_cor(K_src)\n"
    "        # Target's own kernel on target's grid (the reference)\n"
    "        K_tgt = build_correlation_matrix(grid, hp_target['length_scale'], hp_target['constant_value'])\n"
    "        B = cov_to_cor(K_tgt)\n"
    "        ref_norm = np.linalg.norm(B, 'fro')\n"
    "        fro_rel_matrix[i, j] = (\n"
    "            np.linalg.norm(A - B, 'fro') / ref_norm if ref_norm > 1e-12 else np.nan\n"
    "        )\n"
    "\n"
    "labels = [site_label(s) for s in site_ids]\n"
    "fig, ax = plt.subplots(figsize=(max(7, 0.9 * len(labels) + 4),\n"
    "                                 max(6, 0.7 * len(labels) + 3)))\n"
    "sns.heatmap(fro_rel_matrix, annot=True, fmt='.2f', cmap='mako',\n"
    "            xticklabels=labels, yticklabels=labels,\n"
    "            cbar_kws={'label': 'Relative Frobenius distance'}, ax=ax)\n"
    "ax.set_xlabel('Target site'); ax.set_ylabel('Model source site')\n"
    "ax.set_title(f'{CASE_STUDY}: Model-to-Site Correlation Matrix Distance (Frobenius Norm)')\n"
    "plt.tight_layout()\n"
    "plt.show()"
))

# ============================================================
# 8. Variance reduction utility
# ============================================================
cells.append(md(
    "## 8. Variance reduction utility (elbow plot)\n"
    "\n"
    "How quickly does additional sampling reduce GP posterior variance, given an idealized "
    "uniformly-spaced surrogate range and each site's transferred kernel?"
))

cells.append(code(
    "n_eval = 25\n"
    "n_rows, n_cols, figsize = subplot_grid(len(site_ids), max_cols=3, panel_w=4.8, panel_h=3.2)\n"
    "fig, axes = plt.subplots(n_rows, n_cols, figsize=figsize, squeeze=False)\n"
    "axes = axes.flatten()\n"
    "\n"
    "for i, sid in enumerate(site_ids):\n"
    "    ax = axes[i]\n"
    "    for j, model_sid in enumerate(site_ids):\n"
    "        hp = model_dictionary[model_sid]['baseline']['hyperparams_for_omp']\n"
    "        grid = np.linspace(0, 1, 60)\n"
    "        K = build_correlation_matrix(grid, hp['length_scale'], hp['constant_value'])\n"
    "        _, util = omp_variance_reduction(K, n_eval)\n"
    "        ax.plot(range(1, len(util) + 1), util,\n"
    "                marker=MARKERS[j % len(MARKERS)],\n"
    "                color=COLORS[j % len(COLORS)],\n"
    "                label=f'kernel from {site_label(model_sid)}',\n"
    "                markersize=5, linewidth=1)\n"
    "    ax.set_title(f'Site {site_label(sid)}')\n"
    "    ax.set_xlabel('Samples selected')\n"
    "    ax.set_ylabel('Variance reduction utility')\n"
    "    ax.set_ylim(-0.05, 1.05)\n"
    "    if i == 0:\n"
    "        ax.legend(fontsize=7, loc='lower right')\n"
    "hide_unused_axes(axes, len(site_ids))\n"
    "plt.suptitle(f'{CASE_STUDY}: variance reduction elbow plots')\n"
    "plt.tight_layout()\n"
    "plt.show()"
))

# ============================================================
# 9. Main comparison
# ============================================================
cells.append(md(
    "## 9. OMP static vs. stratified random vs. active learning\n"
    "\n"
    "All three strategies are evaluated against the same held-out test set (the held-out fold "
    "of the representative fold, used for plotting only — performance metrics are still aggregated "
    "across folds where applicable). Random selection uses the proportional-stratified-bin sampler "
    "for both case studies."
))

cells.append(code(
    "def gp_metrics_on_test(x_sel, y_sel, x_test, y_test):\n"
    "    \"\"\"Train a GP on selected samples and evaluate RMSE / nRMSE / R^2 on a fixed test set.\"\"\"\n"
    "    nan_out = {'rmse': np.nan, 'nrmse': np.nan, 'r2': np.nan}\n"
    "    if len(x_sel) < 2 or np.ptp(x_sel) < 1e-8 or np.ptp(y_sel) < 1e-8:\n"
    "        return nan_out\n"
    "    try:\n"
    "        _, _, scores = fit_gp(x_sel, y_sel, x_test, y_test)\n"
    "    except Exception:\n"
    "        return nan_out\n"
    "    return {\n"
    "        'rmse':  scores.get('rmse',    np.nan),\n"
    "        'nrmse': scores.get('nrmse',   np.nan),\n"
    "        'r2':    scores.get('r2_test', np.nan),\n"
    "    }\n"
    "\n"
    "comparison = {}\n"
    "METRIC_KEYS = ['rmse', 'nrmse', 'r2']\n"
    "\n"
    "for sid in site_ids:\n"
    "    samples = case_data[sid]['samples']\n"
    "    x_all = samples['surrogate'].to_numpy()\n"
    "    y_all = samples['SSC'].to_numpy()\n"
    "    n = len(x_all)\n"
    "    if n < 5:\n"
    "        continue\n"
    "    rep_fold_idx = model_dictionary[sid]['representative_fold_idx']\n"
    "    fold = model_dictionary[sid]['folds'][rep_fold_idx]\n"
    "    x_test, y_test = fold['x_test'], fold['y_test']\n"
    "    # Build candidate pool from non-test indices\n"
    "    train_indices = sorted(set(range(n)) - set(np.where(\n"
    "        np.isin(x_all, x_test) & np.isin(y_all, y_test))[0].tolist()))\n"
    "    x_pool, y_pool = x_all[train_indices], y_all[train_indices]\n"
    "\n"
    "    n_max = min(OMP_MAX_N, len(x_pool))\n"
    "    n_grid = list(range(2, n_max + 1))\n"
    "\n"
    "    def _curve(order_indices):\n"
    "        \"\"\"Walk the selection order and return per-n metric curves.\"\"\"\n"
    "        out = {m: [] for m in METRIC_KEYS}\n"
    "        for nn in n_grid:\n"
    "            sel = order_indices[:nn]\n"
    "            mvals = gp_metrics_on_test(x_pool[sel], y_pool[sel], x_test, y_test)\n"
    "            for m in METRIC_KEYS:\n"
    "                out[m].append(mvals[m])\n"
    "        return out\n"
    "\n"
    "    # ----- OMP static (transfer from each source site) -----\n"
    "    omp_static = {}\n"
    "    for model_sid in site_ids:\n"
    "        hp = model_dictionary[model_sid]['baseline']['hyperparams_for_omp']\n"
    "        x_min, x_max = x_pool.min(), x_pool.max()\n"
    "        rng = max(x_max - x_min, 1e-8)\n"
    "        xs = (x_pool - x_min) / rng\n"
    "        K = build_correlation_matrix(xs, hp['length_scale'], hp['constant_value'])\n"
    "        order, _ = omp_variance_reduction(K, n_max)\n"
    "        omp_static[model_sid] = {'order': order, 'curves': _curve(order)}\n"
    "\n"
    "    # ----- Active learning (use each source as init) -----\n"
    "    omp_active = {}\n"
    "    for model_sid in site_ids:\n"
    "        hp = model_dictionary[model_sid]['baseline']['hyperparams_for_omp']\n"
    "        order = active_learning_select(x_pool, y_pool,\n"
    "                                       hp['constant_value'], hp['length_scale'],\n"
    "                                       n_total=n_max, batch=ACTIVE_BATCH)\n"
    "        omp_active[model_sid] = {'order': order, 'curves': _curve(order)}\n"
    "\n"
    "    # ----- Stratified random benchmark (median + IQR envelope) -----\n"
    "    rand_metrics = {m: {nn: [] for nn in n_grid} for m in METRIC_KEYS}\n"
    "    for perm in range(N_RAND_PERMS):\n"
    "        rng_perm = np.random.default_rng(RANDOM_SEED + perm)\n"
    "        for nn in n_grid:\n"
    "            idx = proportional_stratified_sample(x_pool, nn, N_STRAT_BINS, rng_perm)\n"
    "            mvals = gp_metrics_on_test(x_pool[idx], y_pool[idx], x_test, y_test)\n"
    "            for m in METRIC_KEYS:\n"
    "                rand_metrics[m][nn].append(mvals[m])\n"
    "    rand_summary = {'n': n_grid}\n"
    "    for m in METRIC_KEYS:\n"
    "        rand_summary[f'{m}_median'] = [float(np.nanmedian(rand_metrics[m][nn])) for nn in n_grid]\n"
    "        rand_summary[f'{m}_q25']    = [float(np.nanpercentile(rand_metrics[m][nn], 25)) for nn in n_grid]\n"
    "        rand_summary[f'{m}_q75']    = [float(np.nanpercentile(rand_metrics[m][nn], 75)) for nn in n_grid]\n"
    "\n"
    "    comparison[sid] = {\n"
    "        'omp_static': omp_static,\n"
    "        'omp_active': omp_active,\n"
    "        'random':     rand_summary,\n"
    "        'n_grid':     n_grid,\n"
    "        'x_pool':     x_pool, 'y_pool': y_pool,\n"
    "        'x_test':     x_test, 'y_test': y_test,\n"
    "    }\n"
    "\n"
    "print('Comparison complete for sites:', [site_label(s) for s in comparison.keys()])"
))

cells.append(code(
    "# Plot RMSE, nRMSE, and R^2 vs. number of samples per site (3 panels per site)\n"
    "METRIC_LABELS = {\n"
    "    'rmse':  'Test RMSE (mg/L)',\n"
    "    'nrmse': 'Test nRMSE',\n"
    "    'r2':    'Test R\\u00b2',\n"
    "}\n"
    "\n"
    "n_sites = len(comparison)\n"
    "if n_sites == 0:\n"
    "    print('No sites had enough samples for the OMP comparison.')\n"
    "else:\n"
    "    fig, axes = plt.subplots(n_sites, 3, figsize=(15, 3.2 * n_sites),\n"
    "                              squeeze=False, sharex='col')\n"
    "    for row_idx, (sid, comp) in enumerate(comparison.items()):\n"
    "        ng = comp['random']['n']\n"
    "        for col_idx, m in enumerate(METRIC_KEYS):\n"
    "            ax = axes[row_idx, col_idx]\n"
    "            ax.fill_between(ng, comp['random'][f'{m}_q25'], comp['random'][f'{m}_q75'],\n"
    "                            color='gray', alpha=0.25, label='Stratified random IQR')\n"
    "            ax.plot(ng, comp['random'][f'{m}_median'], color='black', marker='o',\n"
    "                    markersize=4, label='Stratified random median')\n"
    "            for j, model_sid in enumerate(comp['omp_static'].keys()):\n"
    "                curves = comp['omp_static'][model_sid]['curves']\n"
    "                ax.plot(ng, curves[m], linestyle='--', alpha=0.7,\n"
    "                        color=COLORS[j % len(COLORS)],\n"
    "                        label=f'OMP static (from {site_label(model_sid)})')\n"
    "            for j, model_sid in enumerate(comp['omp_active'].keys()):\n"
    "                curves = comp['omp_active'][model_sid]['curves']\n"
    "                ax.plot(ng, curves[m], linestyle=':', alpha=0.7,\n"
    "                        color=COLORS[j % len(COLORS)],\n"
    "                        label=f'OMP active (from {site_label(model_sid)})')\n"
    "            ax.set_xlabel('Number of training samples')\n"
    "            ax.set_ylabel(METRIC_LABELS[m])\n"
    "            if col_idx == 0:\n"
    "                ax.set_title(f'Site {site_label(sid)}  ({METRIC_LABELS[m]})', loc='left')\n"
    "            else:\n"
    "                ax.set_title(METRIC_LABELS[m], loc='left')\n"
    "            if row_idx == 0 and col_idx == 2:\n"
    "                ax.legend(fontsize=6, ncol=2, loc='lower right')\n"
    "            if m == 'r2':\n"
    "                ax.set_ylim(top=1.05)\n"
    "    plt.suptitle(f'{CASE_STUDY}: OMP vs stratified random vs active learning '\n"
    "                 f'(median of {N_RAND_PERMS} random perms; IQR shaded)')\n"
    "    plt.tight_layout()\n"
    "    plt.show()"
))

# ============================================================
# 10. Time series
# ============================================================
cells.append(md(
    "## 10. Time-series prediction with initial-window training\n"
    "\n"
    "Only applicable to case studies that include a continuous surrogate stream. Restricts the "
    "available samples to those collected during the first `TRAIN_MONTHS` months of the record, "
    "runs OMP using each source site's averaged hyperparameters, trains the GP on the OMP-selected "
    "subset, and predicts on the full continuous time series."
))

cells.append(code(
    "def time_series_prediction(target_sid, model_sid, n_train=TS_N_SAMPLES,\n"
    "                            train_months=TRAIN_MONTHS):\n"
    "    case = case_data[target_sid]\n"
    "    if case['continuous'] is None or len(case['continuous']) == 0:\n"
    "        return None\n"
    "    samples = case['samples'].copy()\n"
    "    if 'datetime' not in samples.columns or samples['datetime'].isna().all():\n"
    "        return None\n"
    "    samples = samples.dropna(subset=['datetime', 'surrogate', 'SSC'])\n"
    "    samples = samples.sort_values('datetime').reset_index(drop=True)\n"
    "    start = samples['datetime'].min()\n"
    "    cutoff = start + pd.DateOffset(months=train_months)\n"
    "    mask = samples['datetime'] <= cutoff\n"
    "    subset = samples[mask].copy()\n"
    "    if len(subset) < n_train:\n"
    "        return None\n"
    "\n"
    "    # OMP-select from initial window using model_sid's averaged hyperparameters\n"
    "    hp = model_dictionary[model_sid]['baseline']['hyperparams_for_omp']\n"
    "    x_sub = subset['surrogate'].to_numpy()\n"
    "    x_min, x_max = x_sub.min(), x_sub.max()\n"
    "    rng_ = max(x_max - x_min, 1e-8)\n"
    "    K = build_correlation_matrix((x_sub - x_min) / rng_, hp['length_scale'], hp['constant_value'])\n"
    "    order, _ = omp_variance_reduction(K, n_train)\n"
    "    sel = order[:n_train]\n"
    "    x_train = x_sub[sel]\n"
    "    y_train = subset['SSC'].to_numpy()[sel]\n"
    "    dates_train = subset['datetime'].to_numpy()[sel]\n"
    "\n"
    "    # Predict on full continuous stream\n"
    "    cont = case['continuous'].sort_values('datetime').reset_index(drop=True)\n"
    "    x_full = cont['surrogate'].to_numpy()\n"
    "    dates_full = cont['datetime'].to_numpy()\n"
    "    gpr, (xg, yg, sg), scores = fit_gp(x_train, y_train)\n"
    "    x_min_t, x_rng_t = scores['x_scale']\n"
    "    y_min_t, y_rng_t = scores['y_scale']\n"
    "    Xc = ((x_full - x_min_t) / x_rng_t).reshape(-1, 1)\n"
    "    ypred_scaled, std_scaled = gpr.predict(Xc, return_std=True)\n"
    "    ypred = ypred_scaled.flatten() * y_rng_t + y_min_t\n"
    "    std = std_scaled.flatten() * y_rng_t\n"
    "    # Interpolate predictions onto the grab-sample timestamps for evaluation\n"
    "    y_obs = samples['SSC'].to_numpy()\n"
    "    obs_t_int = samples['datetime'].astype(np.int64).to_numpy()\n"
    "    full_t_int = dates_full.astype('datetime64[ns]').astype(np.int64)\n"
    "    y_hat_at_obs = np.interp(obs_t_int, full_t_int, ypred)\n"
    "    residuals = y_obs - y_hat_at_obs\n"
    "    rmse_grab = float(np.sqrt(np.mean(residuals ** 2)))\n"
    "    y_rng = float(y_obs.max() - y_obs.min()) if len(y_obs) > 1 else np.nan\n"
    "    nrmse_grab = rmse_grab / y_rng if y_rng and y_rng > 0 else np.nan\n"
    "    ss_res = float(np.sum(residuals ** 2))\n"
    "    ss_tot = float(np.sum((y_obs - np.mean(y_obs)) ** 2)) if len(y_obs) > 1 else 0.0\n"
    "    r2_grab = 1 - ss_res / ss_tot if ss_tot > 0 else np.nan\n"
    "    return {\n"
    "        'dates_full':  dates_full, 'ypred':       ypred, 'std':         std,\n"
    "        'dates_train': dates_train, 'x_train':     x_train, 'y_train':     y_train,\n"
    "        'samples_obs': samples,\n"
    "        'rmse_on_grab':  rmse_grab,\n"
    "        'nrmse_on_grab': nrmse_grab,\n"
    "        'r2_on_grab':    r2_grab,\n"
    "    }\n"
    "\n"
    "ts_results = {}\n"
    "for target in site_ids:\n"
    "    for source in site_ids:\n"
    "        out = time_series_prediction(target, source)\n"
    "        if out is not None:\n"
    "            ts_results[(target, source)] = out\n"
    "\n"
    "if not ts_results:\n"
    "    print('No continuous time-series data for this case study. Skipping time-series plot.')\n"
    "else:\n"
    "    # One panel per (target, source) pair, arranged as targets in rows x sources in cols\n"
    "    targets = sorted({k[0] for k in ts_results.keys()})\n"
    "    sources = sorted({k[1] for k in ts_results.keys()})\n"
    "    n_rows = len(targets); n_cols = len(sources)\n"
    "    fig, axes = plt.subplots(n_rows, n_cols,\n"
    "                              figsize=(6 * n_cols, 3.5 * n_rows),\n"
    "                              squeeze=False, sharex=True, sharey='row')\n"
    "    for r, target in enumerate(targets):\n"
    "        obs = case_data[target]['samples']\n"
    "        for c, source in enumerate(sources):\n"
    "            ax = axes[r, c]\n"
    "            res = ts_results.get((target, source))\n"
    "            if res is None:\n"
    "                ax.set_visible(False)\n"
    "                continue\n"
    "            # 95% confidence band\n"
    "            ax.fill_between(res['dates_full'],\n"
    "                            res['ypred'] - 1.96 * res['std'],\n"
    "                            res['ypred'] + 1.96 * res['std'],\n"
    "                            alpha=0.2, color='#3D7AAB', label='95% CI')\n"
    "            ax.plot(res['dates_full'], res['ypred'],\n"
    "                    color='#1F4E79', linewidth=1.2, label='GP prediction')\n"
    "            # All observed grab samples in white-faced circles\n"
    "            ax.scatter(obs['datetime'], obs['SSC'],\n"
    "                       facecolors='none', edgecolors='black', s=30, linewidths=0.8,\n"
    "                       zorder=4, label='Observed SSC')\n"
    "            # OMP-selected training samples highlighted in red stars\n"
    "            ax.scatter(res['dates_train'], res['y_train'],\n"
    "                       color='#D62728', marker='*', s=120,\n"
    "                       edgecolors='black', linewidths=0.6,\n"
    "                       zorder=6, label=f'OMP training (n={len(res[\"y_train\"])})')\n"
    "            ax.set_title(\n"
    "                f'Target {site_label(target)}  |  source {site_label(source)}\\n'\n"
    "                f'RMSE={res[\"rmse_on_grab\"]:.1f}  '\n"
    "                f'nRMSE={res[\"nrmse_on_grab\"]:.2f}  '\n"
    "                f'R\\u00b2={res[\"r2_on_grab\"]:.2f}',\n"
    "                fontsize=10,\n"
    "            )\n"
    "            if c == 0:\n"
    "                ax.set_ylabel('SSC (mg/L)')\n"
    "            if r == n_rows - 1:\n"
    "                ax.set_xlabel('Date')\n"
    "                for label in ax.get_xticklabels():\n"
    "                    label.set_rotation(30)\n"
    "                    label.set_horizontalalignment('right')\n"
    "            if r == 0 and c == 0:\n"
    "                ax.legend(fontsize=8, loc='upper right')\n"
    "    plt.suptitle(\n"
    "        f'{CASE_STUDY}: time-series prediction with initial-window training '\n"
    "        f'(n_train={TS_N_SAMPLES}, first {TRAIN_MONTHS} months)',\n"
    "        fontsize=12, y=1.01,\n"
    "    )\n"
    "    plt.tight_layout()\n"
    "    plt.show()"
))

# ============================================================
# 11. Calibration analysis
# ============================================================
cells.append(md(
    "## 11. Calibration analysis (Reviewer 3 #11)\n"
    "\n"
    "Per-site 95% interval coverage and Spearman rank correlation between predicted standard "
    "deviation and absolute residual on held-out folds. Aggregated across folds."
))

cells.append(code(
    "calib_rows = []\n"
    "for sid in site_ids:\n"
    "    b = model_dictionary[sid]['baseline']\n"
    "    calib_rows.append({\n"
    "        'site': site_label(sid),\n"
    "        'coverage_95': round(b['coverage_95_median'], 3),\n"
    "        'unc_err_rho': round(b['unc_err_rho_median'], 3),\n"
    "    })\n"
    "calib_df = pd.DataFrame(calib_rows)\n"
    "calib_df"
))

cells.append(code(
    "# Diagnostic scatter: predicted std vs absolute residual, pooled across folds\n"
    "n_rows, n_cols, figsize = subplot_grid(len(site_ids), max_cols=3, panel_w=4.5, panel_h=3.2)\n"
    "fig, axes = plt.subplots(n_rows, n_cols, figsize=figsize, squeeze=False)\n"
    "axes = axes.flatten()\n"
    "for i, sid in enumerate(site_ids):\n"
    "    ax = axes[i]\n"
    "    stds, residuals = [], []\n"
    "    for f in model_dictionary[sid]['folds'].values():\n"
    "        if 'std_test' not in f['scores'] or 'ypred_test' not in f['scores']:\n"
    "            continue\n"
    "        stds.extend(np.asarray(f['scores']['std_test']).tolist())\n"
    "        residuals.extend(np.abs(np.asarray(f['y_test']) -\n"
    "                                  np.asarray(f['scores']['ypred_test'])).tolist())\n"
    "    if len(stds) < 3:\n"
    "        ax.set_visible(False); continue\n"
    "    stds = np.array(stds); residuals = np.array(residuals)\n"
    "    ax.scatter(stds, residuals, alpha=0.6)\n"
    "    ax.set_xlabel('Predicted std')\n"
    "    ax.set_ylabel('|residual|')\n"
    "    if np.std(stds) > 1e-12:\n"
    "        rho, _ = spearmanr(stds, residuals)\n"
    "    else:\n"
    "        rho = np.nan\n"
    "    ax.set_title(f'Site {site_label(sid)}  (\\u03c1={rho:.2f})')\n"
    "hide_unused_axes(axes, len(site_ids))\n"
    "plt.suptitle(f'{CASE_STUDY}: predicted std vs. absolute residual')\n"
    "plt.tight_layout()\n"
    "plt.show()"
))

# ============================================================
# 12. Process-relevance analysis
# ============================================================
cells.append(md(
    "## 12. Process-relevance analysis (Reviewer 3 #6/#8)\n"
    "\n"
    "Do OMP picks preferentially capture upper-SSC-quartile / upper-surrogate-quartile "
    "conditions vs. matched bootstrapped random selections? Done per site with N_top = 6 and 10."
))

cells.append(code(
    "process_rows = []\n"
    "for sid in site_ids:\n"
    "    samples = case_data[sid]['samples']\n"
    "    x_all = samples['surrogate'].to_numpy()\n"
    "    y_all = samples['SSC'].to_numpy()\n"
    "    if len(x_all) < 6:\n"
    "        continue\n"
    "    hp = model_dictionary[sid]['baseline']['hyperparams_for_omp']\n"
    "    x_min, x_max = x_all.min(), x_all.max()\n"
    "    rng_ = max(x_max - x_min, 1e-8)\n"
    "    xs = (x_all - x_min) / rng_\n"
    "    K = build_correlation_matrix(xs, hp['length_scale'], hp['constant_value'])\n"
    "    order, _ = omp_variance_reduction(K, min(OMP_MAX_N, len(x_all)))\n"
    "    for n_top in (6, 10):\n"
    "        if n_top > len(x_all):\n"
    "            continue\n"
    "        s = omp_vs_random_summary(x_all, y_all, order, n_top=n_top, n_random=200)\n"
    "        s['site'] = site_label(sid)\n"
    "        process_rows.append(s)\n"
    "if not process_rows:\n"
    "    print('No site had enough samples for the process-relevance analysis.')\n"
    "    process_df = pd.DataFrame()\n"
    "else:\n"
    "    process_df = pd.DataFrame(process_rows)\n"
    "    cols = ['site', 'n_top', 'omp_frac_top25_ssc', 'rand_frac_top25_ssc_mean',\n"
    "            'rand_frac_top25_ssc_p95', 'omp_frac_top25_surr',\n"
    "            'rand_frac_top25_surr_mean', 'rand_frac_top25_surr_p95']\n"
    "    process_df = process_df[cols].round(3)\n"
    "process_df"
))

cells.append(code(
    "# Visual: overlay OMP top-10 picks vs. one random draw of size 10\n"
    "n_rows, n_cols, figsize = subplot_grid(len(site_ids), max_cols=3, panel_w=4.5, panel_h=3.2)\n"
    "fig, axes = plt.subplots(n_rows, n_cols, figsize=figsize, squeeze=False)\n"
    "axes = axes.flatten()\n"
    "rng_ = np.random.default_rng(RANDOM_SEED)\n"
    "for i, sid in enumerate(site_ids):\n"
    "    ax = axes[i]\n"
    "    samples = case_data[sid]['samples']\n"
    "    x_all = samples['surrogate'].to_numpy()\n"
    "    y_all = samples['SSC'].to_numpy()\n"
    "    if len(x_all) < 6:\n"
    "        ax.set_visible(False); continue\n"
    "    hp = model_dictionary[sid]['baseline']['hyperparams_for_omp']\n"
    "    x_min, x_max = x_all.min(), x_all.max()\n"
    "    rng__ = max(x_max - x_min, 1e-8)\n"
    "    K = build_correlation_matrix((x_all - x_min) / rng__,\n"
    "                                  hp['length_scale'], hp['constant_value'])\n"
    "    order, _ = omp_variance_reduction(K, min(10, len(x_all)))\n"
    "    n_top = min(10, len(x_all))\n"
    "    omp_idx = order[:n_top]\n"
    "    rand_idx = rng_.choice(len(x_all), size=n_top, replace=False)\n"
    "    ax.scatter(x_all, y_all, color='lightgray', s=25, label='All samples')\n"
    "    ax.scatter(x_all[rand_idx], y_all[rand_idx],\n"
    "               facecolors='none', edgecolors='C1', s=80, label=f'Random top-{n_top}')\n"
    "    ax.scatter(x_all[omp_idx], y_all[omp_idx],\n"
    "               color='C3', s=40, label=f'OMP top-{n_top}', zorder=5)\n"
    "    ax.set_xlabel(SURR_LABEL); ax.set_ylabel('SSC (mg/L)')\n"
    "    ax.set_title(f'Site {site_label(sid)}')\n"
    "    if i == 0:\n"
    "        ax.legend(fontsize=8)\n"
    "hide_unused_axes(axes, len(site_ids))\n"
    "plt.suptitle(f'{CASE_STUDY}: OMP vs random top picks (process-relevance)')\n"
    "plt.tight_layout()\n"
    "plt.show()"
))

# ============================================================
# Closing notes
# ============================================================
cells.append(md(
    "## Done\n"
    "\n"
    "All the analyses needed for the response-to-reviewers are in this notebook. "
    "To rerun for the other case study, change `CASE_STUDY` at the top and re-run all cells.\n"
    "\n"
    "**Outputs to drop into the manuscript / SI**:\n"
    "- `summary_df` (§6): fold-aggregated per-site metrics (RMSE, nRMSE, R², coverage, ρ, kernel hyperparameters).\n"
    "- Frobenius heatmap (§7): the transferability diagnostic.\n"
    "- Variance reduction elbow figure (§8).\n"
    "- OMP vs. stratified random vs. active learning per-site figure (§9).\n"
    "- Time-series prediction figure (§10) — MN only.\n"
    "- `calib_df` (§11) + predicted-std-vs-residual scatters.\n"
    "- `process_df` (§12) + OMP-vs-random overlay scatter."
))

# ============================================================
# Build notebook
# ============================================================
notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.10"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

import sys
out = sys.argv[1] if len(sys.argv) > 1 else "soft_sensing_unified.ipynb"
with open(out, "w") as f:
    json.dump(notebook, f, indent=1)
print("wrote", out, f"({len(cells)} cells)")
